server:
  port: 8081

spring:
  application:
    name: analysis-service
  
  data:
    redis:
      host: localhost
      port: 6379
    bootstrap-servers: my-kafka.parkit.svc.cluster.local:9092오
    properties:
      api.version.request: true
    consumer:
      group-id: analysis-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO
    com.parkit.analysis: DEBUG
    org.springframework.data.redis: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# 프로메테우스 메트릭스 설정 추가
management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
  endpoint:
    prometheus:
      enabled: true