server:
  port: 8083

spring:
  application:
    name: report-service
  
  data:
    mongodb:
      uri: mongodb://mongodb:27017/parkit

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: report-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: INFO
    com.parkit.report: DEBUG
    org.springframework.kafka: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
