server:
  port: 8082

spring:
  application:
    name: socket-service

  kafka:
    bootstrap-servers: my-kafka:9092
    consumer:
      group-id: socket-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

parkit:
  kafka:
    topics:
      coachingEvent: coaching-event

logging:
  level:
    root: INFO
    com.parkit.socket: DEBUG
    org.springframework.kafka: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# 프로메테우스 endpoint!
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
